### ISSUE TITLE
[documentation] Documentation is required

### ISSUE THREAD

**Issue by my-Shadows** [my-Shadows/javafx-#1]
Please provide detailed documentation, languages in the project, and technologies used

**Comment by future2023922** [comment]
# JavaFx

This project is a graphical program formed by Java programming.A JavaFX application that creates a simple file explorer with tabs for viewing text files and images. 

## Table of Contents
- [Installation](#installation)
- [Usage](#usage)
- [File Types](#file-types)
- [Contributing](#contributing)
- [License](#license)

## Installation

The `Main` class extends the `Application` class, which is the entry point for JavaFX applications. It overrides the `start` method to configure and display the application's primary stage.

## Usage

The main class contains several instance variables:
   - `tabPane`: A `TabPane` that holds the tabs for displaying file content.
   - `fileListView`: A custom class (`FileListView`) that extends `ListView` and displays the files in a directory.
   - `root`: The root `BorderPane` that provides a layout for the application's UI.
   - `files`: An array of `File` objects representing the files in a specific directory.

In the `start` method, you configure the UI components and set up event handlers. The `fileListView` is added to the left side of the `root`, while the `tabPane` is placed in the center. The `InitFiles` method is called to populate the `fileListView` with files from a specified directory.

The `main` method is the entry point for the Java application. It launches the JavaFX application by calling `launch(args)`.

## Contributing

Contributions to FileItem are welcome! If you encounter any issues or have suggestions for improvements, please feel free to open an issue or submit a pull request on [GitHub].

## License

This project is licensed under the MIT License. See the [LICENSE](LICENSE) file for more information.

**Comment by my-Shadows** [comment]
First of all, thank you for providing some documentation for my project, but there are still some problems below, I hope you can correct them.
Overall, the README file provides a good starting point for understanding the project. However, there are a few areas where improvements can be made:

1. **Project Dependencies**: It would be helpful to include information about any external dependencies or libraries required for running the project. 

2. **Installation Instructions**: Expand on the installation section by providing step-by-step instructions on how to set up and configure the project. This should include any necessary configuration steps, such as setting up the JavaFX runtime environment and configuring the IDE or build tools.

3. **Usage Examples**: Provide some sample code or an example on how to use the file explorer program. This can help users quickly understand how to interact with the application and utilize its features effectively.

4. **Formatting**: Ensure consistent formatting throughout the README file. Use proper headings, bullet lists, code formatting, and markdown syntax to improve readability and maintain a professional appearance.

Thanks a lot.

**Comment by future2023922** [comment]
# JavaFx

This project is a JavaFX application that creates a simple file explorer with tabs for viewing text files and images.

## Installation

To run this project, you need to have Java and JavaFX installed on your system. Follow the steps below to get started:

1. Install Java Development Kit (JDK) if you don't have it installed already. You can download it from the Oracle website or use a package manager for your operating system.

2. Install JavaFX. Starting from Java 11, JavaFX is no longer bundled with the JDK, so you need to download it separately. You can download the JavaFX SDK from the OpenJFX website.

3. Set up your development environment. This project can be built and run using an Integrated Development Environment (IDE) such as IntelliJ IDEA or Eclipse. Make sure to configure the IDE to use the JDK and JavaFX correctly.

## Usage

The main class `Main` extends the `Application` class, which is the entry point for JavaFX applications. It overrides the `start` method to configure and display the application's primary stage.

The UI components are set up in the `start` method. The `TabPane` is used to display tabs for each file, and a custom class `FileListView` is used to display the files in a directory. The `InitFiles` method is called to populate the `FileListView` with files from a specified directory.

To run the application, execute the `main` method, which launches the JavaFX application. The file explorer UI will be displayed, allowing you to browse and view files.

## File Types

This file explorer supports two types of files: text files and images.

- Text Files: When a text file is selected, a new tab is created in the `TabPane`, and the contents of the text file are displayed using a `TextArea`.

- Images: When an image file is selected, a new tab is created in the `TabPane`, and the image is displayed using an `ImageView`.

## Contributing

Contributions to this project are welcome! If you encounter any issues or have suggestions for improvements, please feel free to open an issue or submit a pull request on [GitHub repository](https://github.com/your/repository).

## License

This project is licensed under the MIT License. See the [LICENSE](LICENSE) file for more information.

**Comment by my-Shadows** [comment]
OK，fine
